### ISSUE TITLE
输出文件命名策略导致同分异构的结构丢失

### ISSUE THREAD

**Issue by hust-rxchen** [stanfordbshan/HTMACat-kit#42]
## 你使用的 HTMACat 是什么版本，什么环境？

> HTMACat 版本: 
> 1.0.5, development
> 环境: 
> python 3.8.6

## 你遇到什么问题了？

> 现在生成的vasp结构文件，命名时使用的是分子式，如果输入文件使用SMILES，吸附物种出现异构情况时，会覆盖先生成的同分子式的同名文件，导致输出结果缺失。
案例CO2_reduction，命令行运行输出结果：
  O[C][O] adsorption on Au (111) substrate are construct with 4 configurations!
  [O][CH][O] adsorption on Au (111) substrate are construct with 4 configurations!
  O[C]O adsorption on Au (111) substrate are construct with 4 configurations!
  [CH2]O adsorption on Au (111) substrate are construct with 4 configurations!
  [CH][O] adsorption on Au (111) substrate are construct with 4 configurations!
  [CH]O adsorption on Au (111) substrate are construct with 4 configurations!
其中O[C][O] 和 [O][CH][O]的分子式都为CHO2，最终只生成了20个结构文件

## 是否已经浏览过Issues仍无法解决？

> 是的

## 你期望的结果

> 可以参照之前一个版本的策略，Model读取的字符串是什么就在命名里使用什么，避免混淆

## 给出程序界面截图、后台运行日志或配置文件

> 

> 其它问题提供后台日志

**Comment by ZhangLiu-HUST** [comment]
定义命名规则
